header_text = """Version_1
MapProperties{
mapID=
mapTitle=GenMaze
mapDescription=Generated by GenMaze
mapTags=generated,maze
isCampaign=False
faces=
mapEnemyCount=
music=Nether
lavaColor=0,0.05,0.15,1
lavaEmissiveColor=0.1628999,0.5710551,0.905,1
waterColor=0,0.05,0.15,1
waterEmissiveColor=0,0,0,1
wasteColor=0,0.372,0.45,1
wasteEmissiveColor=0.58,0.823,0.741,1
}
Colors{
Default=1,1,1,1
Grey=0.31,0.31,0.31,1
Black=0,0,0,1
Red=1,0,0,1
Green=0,1,0,1
Blue=0,0,1,1
Yellow=1,0.87,0,1
}
"""
